name: /cluster/tufts/cowenlab/wlou01/condaenv/biosolu
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aom=3.9.1
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - attr=2.5.2
  - binaryornot=0.4.4
  - biopython=1.84
  - black=25.1.0
  - blast=2.16.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - cookiecutter=2.6.0
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - curl=8.11.1
  - cython=3.1.3
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - einops=0.8.1
  - entrez-direct=22.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.17.0
  - flatbuffers=24.12.23
  - freetype=2.12.1
  - fsspec=2025.2.0
  - gast=0.6.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - git-lfs=3.7.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-pasta=0.2.0
  - h2=4.2.0
  - h5py=3.12.1
  - hdf5=1.14.4
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.5.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcap=2.75
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.11.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libde265=1.0.15
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.2
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgrpc=1.67.1
  - libheif=1.19.5
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopenblas=0.3.28
  - libpmix=5.0.8
  - libpng=1.6.46
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libudev1=257.7
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lightning=2.5.4
  - lightning-utilities=0.15.2
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpi4py=4.1.0
  - mpmath=1.3.0
  - mypy_extensions=1.1.0
  - namex=0.0.8
  - ncbi-vdb=3.1.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - ocl-icd=2.3.2
  - opencl-headers=2024.10.24
  - openjpeg=2.5.3
  - openmpi=5.0.8
  - openssl=3.5.2
  - opt_einsum=3.4.0
  - optree=0.14.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.5
  - pathspec=0.12.1
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.105
  - perl-encode=3.19
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.62
  - perl-types-serialiser=1.01
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=24.3.1
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.2.10
  - python-slugify=8.0.4
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.4
  - pytorch-mutex=1.0
  - pytorch-ranger=0.1.1
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - rav1e=0.6.6
  - rdma-core=59.0
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - rpsbproc=0.5.0
  - scipy=1.15.2
  - setuptools=75.6.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=2.5.0
  - text-unidecode=1.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.2.1
  - torch-optimizer=0.3.0
  - torchaudio=2.5.1
  - torchmetrics=1.8.1
  - torchvision=0.20.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - ucc=1.5.0
  - ucx=1.19.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wget=1.21.4
  - wheel=0.45.1
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.15
    - aiosignal==1.4.0
    - antlr4-python3-runtime==4.9.3
    - async-timeout==5.0.1
    - attrs==25.3.0
    - cachetools==5.5.1
    - certifi==2025.1.31
    - fair-esm==2.0.0
    - frozenlist==1.7.0
    - google-auth==2.38.0
    - google-auth-oauthlib==1.2.1
    - grpcio==1.70.0
    - huggingface-hub==0.28.1
    - hydra-core==1.3.2
    - keras==2.15.0
    - libclang==18.1.1
    - markdown==3.7
    - ml-dtypes==0.2.0
    - multidict==6.6.4
    - numpy==1.26.4
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - propcache==0.3.2
    - protobuf==4.25.6
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pytz==2024.2
    - raygun==0.2.3
    - regex==2024.11.6
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - safetensors==0.5.2
    - sentencepiece==0.2.0
    - shellingham==1.5.4
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - tokenizers==0.21.0
    - transformers==4.48.3
    - typer==0.17.3
    - tzdata==2024.2
    - wrapt==1.14.1
    - yarl==1.20.1
